"use client";

import { Icons } from "@/components/ui/icons";

export interface AIGeneratedBadgeProps {
  /** Optional source summary to show on hover */
  sourceSummary?: string;
  className?: string;
}

export function AIGeneratedBadge({ sourceSummary, className = "" }: AIGeneratedBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 ${className}`}
      title={sourceSummary ?? "Generated by AI Content Factory"}
    >
      <span className="opacity-80">{Icons.sparkles}</span>
      AI Generated
    </span>
  );
}
