"use client";

import { Card } from "@/components/ui/Card";
import { Icons } from "@/components/ui/icons";
import {
  buildGenerationSourceSummary,
  type AIGenerationRecord,
} from "@/lib/admin/ai-generation-lookup";

export interface AIGenerationSourcePanelProps {
  record: AIGenerationRecord;
}

export function AIGenerationSourcePanel({ record }: AIGenerationSourcePanelProps) {
  const summary = buildGenerationSourceSummary(record.generationParams);
  const track = record.generationParams.track as string | undefined;
  const system = record.generationParams.systemName as string | undefined;
  const topic = record.generationParams.topicName as string | undefined;
  const objective = record.generationParams.objective as string | undefined;

  return (
    <Card>
      <h3 className="font-semibold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
        <span className="text-indigo-500">{Icons.sparkles}</span>
        AI Generation Source
      </h3>
      <p className="text-sm text-slate-600 dark:text-slate-400 mb-3">
        This content was generated by the AI Content Factory. Summary of generation context (no full prompts stored):
      </p>
      <dl className="text-sm space-y-2">
        <div className="flex gap-2">
          <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">Summary</dt>
          <dd className="text-slate-700 dark:text-slate-300">{summary}</dd>
        </div>
        {track && (
          <div className="flex gap-2">
            <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">Track</dt>
            <dd className="text-slate-700 dark:text-slate-300">{track.toUpperCase()}</dd>
          </div>
        )}
        {system && (
          <div className="flex gap-2">
            <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">System</dt>
            <dd className="text-slate-700 dark:text-slate-300">{system}</dd>
          </div>
        )}
        {topic && (
          <div className="flex gap-2">
            <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">Topic</dt>
            <dd className="text-slate-700 dark:text-slate-300">{topic}</dd>
          </div>
        )}
        {objective && (
          <div className="flex gap-2">
            <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">Focus</dt>
            <dd className="text-slate-700 dark:text-slate-300 line-clamp-2">{objective}</dd>
          </div>
        )}
        <div className="flex gap-2">
          <dt className="text-slate-500 dark:text-slate-400 w-24 shrink-0">Generated</dt>
          <dd className="text-slate-700 dark:text-slate-300">
            {record.generatedAt
              ? new Date(record.generatedAt).toLocaleString()
              : "—"}
          </dd>
        </div>
      </dl>
    </Card>
  );
}
