import { ADMIN_ROUTES } from "./admin-routes";

export const PRIMARY_NAV = [
  { href: "/dashboard", label: "Dashboard", icon: "layout-dashboard" },
  { href: "/study-plan", label: "Study Plan", icon: "calendar" },
  { href: "/questions", label: "Questions", icon: "help-circle" },
  { href: "/topics", label: "Topic Hub", icon: "book" },
  { href: "/pre-practice", label: "Pre-Practice Exam", icon: "file-check" },
  { href: "/adaptive-exam", label: "Adaptive Exam", icon: "trending-up" },
  { href: "/practice", label: "Practice Exams", icon: "clipboard-list" },
  { href: "/flashcards", label: "Flashcards", icon: "layers" },
  { href: "/videos", label: "Videos", icon: "video" },
  { href: "/study-guides", label: "Study Guides", icon: "book-open" },
  { href: "/notebook", label: "Notebook", icon: "notebook" },
  { href: "/ai-tutor", label: "Jade Tutor", icon: "sparkles" },
  { href: "/high-yield", label: "High-Yield", icon: "layers" },
  { href: "/progress", label: "Progress", icon: "trending-up" },
  { href: "/weak-areas", label: "Weak Areas", icon: "trending-up" },
  { href: "/strength-report", label: "Strength Report", icon: "trending-up" },
  { href: "/confidence-calibration", label: "Confidence", icon: "bar-chart" },
  { href: "/billing", label: "Billing", icon: "credit-card" },
  { href: "/profile", label: "Profile", icon: "user" },
] as const;

export const ADMIN_NAV = [
  { href: "/dashboard", label: "Main app", icon: "layout-dashboard" },
  { href: ADMIN_ROUTES.OVERVIEW, label: "Overview", icon: "layout-dashboard" },
  { href: ADMIN_ROUTES.CURRICULUM, label: "Curriculum", icon: "book" },
  { href: ADMIN_ROUTES.SYSTEM_BUNDLES, label: "System Bundles", icon: "book" },
  { href: ADMIN_ROUTES.QUESTIONS, label: "Questions", icon: "help-circle" },
  { href: ADMIN_ROUTES.STUDY_GUIDES, label: "Study Guides", icon: "book-open" },
  { href: ADMIN_ROUTES.FLASHCARDS, label: "Flashcards", icon: "layers" },
  { href: ADMIN_ROUTES.VIDEOS, label: "Videos", icon: "video" },
  { href: ADMIN_ROUTES.MEDIA_RIGHTS, label: "Media Rights", icon: "shield" },
  { href: ADMIN_ROUTES.REVIEW_QUEUE, label: "Review Queue", icon: "inbox" },
  { href: ADMIN_ROUTES.PUBLISH_QUEUE, label: "Publish Queue", icon: "send" },
  { href: ADMIN_ROUTES.AI_PROMPTS, label: "AI Prompts", icon: "cpu" },
  { href: ADMIN_ROUTES.MASTERY_RULES, label: "Mastery Rules", icon: "trending-up" },
  { href: ADMIN_ROUTES.RECOMMENDATIONS, label: "Recommendations", icon: "sparkles" },
  { href: ADMIN_ROUTES.ISSUE_REPORTS, label: "Issue Reports", icon: "inbox" },
  { href: ADMIN_ROUTES.HIGH_YIELD, label: "High-Yield", icon: "layers" },
  { href: ADMIN_ROUTES.EXAMS, label: "Exam Assembly", icon: "clipboard-list" },
  { href: ADMIN_ROUTES.BATCH_PLANNER, label: "Batch Planner", icon: "clipboard-list" },
  { href: ADMIN_ROUTES.CONTENT_INVENTORY, label: "Content Inventory", icon: "bar-chart" },
  { href: ADMIN_ROUTES.LAUNCH_READINESS, label: "Launch Readiness", icon: "file-check" },
  { href: ADMIN_ROUTES.BLUEPRINT_COVERAGE, label: "Blueprint Coverage", icon: "bar-chart" },
  { href: ADMIN_ROUTES.ANALYTICS, label: "Analytics", icon: "bar-chart" },
] as const;

export const PUBLIC_NAV = [
  { href: "/", label: "Home" },
  { href: "/pricing", label: "Pricing" },
  { href: "/faq", label: "FAQ" },
  { href: "/login", label: "Sign in" },
] as const;
